package com.example.productmicroservice.model;

public enum Category {
    ELECTRONICS,
    FASHION,
    HOME_AND_KITCHEN,
    BEAUTY_AND_PERSONAL_CARE,
    SPORTS_AND_OUTDOORS,
    HEALTH_AND_WELLNESS,
    BOOKS_AND_STATIONERY,
    TOYS_AND_GAMES,
    AUTOMOTIVE,
    HOME_IMPROVEMENT,
    PET_SUPPLIES,
    BABY_AND_KIDS,
    FOOD_AND_BEVERAGES,
    ELECTRONICS_ACCESSORIES,
    OFFICE_SUPPLIES,
    OTHERS
}
